name: Latest blog post workflow

on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: ./profile/README.md
          comment_tag_name: "POST-LIST"
          feed_list: "https://lostfocus.de/tag/php-weather/feed/,https://phpc.social/@phpweather.rss,https://github.com/php-weather/common/releases.atom,https://github.com/php-weather/http-provider/releases.atom,https://github.com/php-weather/brightsky/releases.atom,https://github.com/php-weather/open-meteo/releases.atom,https://github.com/php-weather/openweathermap/releases.atom,https://github.com/php-weather/tomorrow/releases.atom"
          feed_names: "Notes,Mastodon,common,http-provider,brightsky,open-meteo,openweathermap,tomorrow"
          template: "$newline - *$feedName:* [$title]($url) $newline"
          max_post_count: 10
